version: '3.8'

services:
  db_test:
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=y_lab_fastapi_test
    ports:
      - "5432:5433"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d y_lab_fastapi_test"]
      interval: 10s
      timeout: 5s
      retries: 5


  test_web_2_app:
    container_name: test_2_app
    build:
      context: .
      dockerfile: Dockerfile
    command: pytest -vv tests/tester_menu.py
    volumes:
      - .:/app
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=y_lab_fastapi_test
      - DB_PORT=${DB_PORT}
      - DB_HOST=db_test
      - SQLALCHEMY_SILENCE_UBER_WARNING=1
    ports:
      - "8080:8080"
    depends_on:
      db_test:
        condition: service_healthy

  redis:
    image: redis
    container_name: 'redis-server'
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: [ "redis-server"]
