version: '3.8'

services:
  test_web_2_app:
    container_name: test_2_app
    build:
      context: .
      dockerfile: Dockerfile
    command: "pytest -vv tests/tester_menu.py"
    volumes:
      - .:/app
    networks:
      - web_2_network
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SQLALCHEMY_SILENCE_UBER_WARNING=1
    ports:
      - "8080:8080"

networks:
  web_2_network:
    external: true