version: '3.8'

services:
  test_web_2_app:
    container_name: test_2_app
    build:
      context: .
      dockerfile: Dockerfile
    command: "pytest -vv tests/tester_menu.py" # && pytest -vv tests/tester_menu.py"
    volumes:
      - .:/app
    networks:
      - web_test
    environment:
      - DATABASE_URL=sqlite:///./test.db
      - SQLALCHEMY_SILENCE_UBER_WARNING=1
    ports:
      - "8080:8080"

networks:
  web_test:
    name: web_test