"""First migration

Revision ID: fc69e80fbf37
Revises: bbdf800c0df2
Create Date: 2023-01-25 16:51:49.795794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc69e80fbf37'
down_revision = 'bbdf800c0df2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
